# Generated by Django 3.1.3 on 2020-11-02 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='newpost',
            name='update',
        ),
        migrations.AddField(
            model_name='newpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
